"""
Configuration for the IELTS Listening audio generation pipeline.

Who speaks with which accent/gender now lives in each test's "speakers" block
in data/tests.json (generated by pdf_to_json.py). SPEAKER_PROFILES below is
only a fallback for tests that don't carry their own cast.
"""

import os

try:
    from dotenv import load_dotenv
    load_dotenv()  # reads a local .env file (git-ignored) into os.environ, if present
except ImportError:
    pass

# ---------------------------------------------------------------------------
# API
# ---------------------------------------------------------------------------
ELEVENLABS_API_KEY = os.environ.get("ELEVENLABS_API_KEY", "")
ELEVENLABS_MODEL_ID = os.environ.get("ELEVENLABS_MODEL_ID", "eleven_v3")
ELEVENLABS_BASE_URL = "https://api.elevenlabs.io/v1"

# No API key -> MOCK mode (placeholder hum clips, no credits spent).
MOCK_MODE = not bool(ELEVENLABS_API_KEY)

# Rewrite "I will" -> "I'll" etc. in the text sent to the TTS API only.
ENABLE_CONTRACTIONS = True

# ---------------------------------------------------------------------------
# Voice ID pools, by accent and gender -- from 11labs_voiceID.xlsx.
# If a voice always whispers or sounds wrong, delete its ID from the pool.
# ---------------------------------------------------------------------------
ACCENT_GENDER_POOLS = {
    "British": {
        "male": [
            "Tx7VLgfksXHVnoY6jDGU", "aFyw0oiXW7dzKF4o7woX", "jRAAK67SEFE9m7ci5DhD",
            "llNlEi50DSCIEuoOIaH7", "bPwYieWFNPo6MSKrfS6j", "lUTamkMw7gOzZbFIwmq4",
            "ZVE5GaLwU3HuFONCXSPz", "P4DhdyNCB4Nl6MA0sL45", "fATgBRI8wg5KkDFg8vBd",
            "VsQmyFHffusQDewmHB5v",
        ],
        "female": [
            "kBag1HOZlaVBH7ICPE8x", "rqAWw1SQ1PYMM00B9ZTb", "1hlpeD1ydbI2ow0Tt3EW",
            "1YfmfuouRyRwVbpAZP7R", "Op72Fm6dzjYuyMTp6FBl", "HXOwtW4XU7Ne6iOiDHTl",
            "QqLi9iPR1Lu3I40qrGjU", "skNETUxpPRQlRrLwu88x",
        ],
    },
    "Australian": {
        "male": ["3DkcznWTIDSnX3f0J6DG", "gJaX474VQb1E5GJBSCPh", "QLOrGSLtlFUlfQRSaOtQ"],
        "female": [
            "ssxGjYJjpi2zZlztJhZU", "319bKIhetA5g6tmywrwj", "rSeWUeOepJe3YA3pacAe",
            "tyZ2vPoArunQ8LpRQu6x", "Bu8XtNMginOxwiByyW2I", "TvYCW7acMEs9RZ2kkcBn",
            "U9VgC8Xinl7nnNsyDd3J",
        ],
    },
    "Canadian": {
        "male": [
            "DMljQdXAGELCjF2K6UHK", "klfO7uDt4WsjhNnhI2HZ", "y26Xv4PQ7Ftbu1mfaEFY",
            "lAyepFdMFNSZ30LU9edN", "bBE6oKIBXZhM23o3YoXb", "mI8xLTBNjMXAf31I4xlB",
            "w4Z9gYJrajAuQmheNbVn", "epkQ8pqDcY2DxhmFi8xl", "ZN36quYSeOCuxo0IhFKk",
            "frBOG9T06d0Zw1PEvoZN",
        ],
        "female": ["JpjuQfOymR78GvGgYe0U", "ClKfJnuqp0hQ7Ax41F4w"],
    },
    "American": {
        "male": [
            "wBXNqKUATyqu0RtYt25i", "s3TPKV1kjDlVtZbl4Ksh", "8Ln42OXYupYsag45MAUy",
            "ev2kMR9ZJZZsemuogS5u", "pVnrL6sighQX7hVz89cp", "J2FGlQG8Gd7x8uEDt2H8",
            "1IKfgBmzdwnmAUPnryb3",
        ],
        "female": [
            "k9KXsQFJqzAoomTCOrJB", "xFPwxsyzPJFEaL61n2ms", "PStJ2DzQnh8zxG5PDf1s",
            "KWDD3Wyq30ZF5NEL01EJ", "rCuVrCHOUMY3OwyJBJym", "LJwPgeJYv0dNJzEtXVO6",
            "Fc5CaIGWKvLHapoOSM2K", "K7W7zLWeGoxU9YqWoB7A", "DODLEQrClDo8wCz460ld",
            "mC104ON19u9NruNfYC3j",
        ],
    },
}

# ---------------------------------------------------------------------------
# Narrator: ONE fixed voice for every test (not randomly picked per test).
# To change the narrator, put a different voice ID here -- e.g. any ID from
# the British female list above. Nobody else in a test is ever given this voice.
# ---------------------------------------------------------------------------
NARRATOR_VOICE_ID = "HXOwtW4XU7Ne6iOiDHTl"

# The narrator is read at maximum stability (v3 "Robust") so every
# announcement sounds like the same calm person, and with a fixed seed so
# repeated requests come out as close to identical as ElevenLabs allows.
NARRATOR_VOICE_SETTINGS = {"stability": 1.0, "similarity_boost": 0.8}
NARRATOR_SEED = 12345

# Fallback only -- tests in data/tests.json carry their own "speakers" cast.
SPEAKER_PROFILES = {
    "narrator": {"accent": "British", "gender": "female", "desc": "Neutral IELTS narrator"},
    "NARRATOR": {"accent": "British", "gender": "female", "desc": "Neutral IELTS narrator"},
    "Lecturer": {"accent": "British", "gender": "male", "desc": "Section 4 lecturer"},
    "University Lecturer": {"accent": "British", "gender": "male", "desc": "Section 4 lecturer"},
}

DEFAULT_PROFILE = {"accent": "British", "gender": "female", "desc": "Fallback voice for an unlisted speaker"}

# ---------------------------------------------------------------------------
# Voice settings.
# Eleven v3 stability: 0.0 = Creative (expressive but can whisper, go breathy
# or drift to a different-sounding voice), 0.5 = Natural, 1.0 = Robust (most
# consistent, least responsive to tags). 0.5 keeps each character sounding
# like the same person. If a voice still drifts, raise it to 1.0.
# ---------------------------------------------------------------------------
DEFAULT_VOICE_SETTINGS = {
    "stability": 0.5,
    "similarity_boost": 0.8,
}

TAG_SETTINGS = {"default": DEFAULT_VOICE_SETTINGS}   # kept for compatibility

# Per-voice_id overrides, e.g. {"kBag1HOZlaVBH7ICPE8x": {"stability": 1.0, "similarity_boost": 0.8}}
VOICE_SETTINGS_OVERRIDES: dict[str, dict] = {}
VOICE_SETTINGS_OVERRIDES.setdefault(NARRATOR_VOICE_ID, NARRATOR_VOICE_SETTINGS)

# ---------------------------------------------------------------------------
# Eleven v3 tags.
# The scripts' tags ([warm], [hesitant], [clear], ...) are director's notes.
# Only a few map safely to real v3 tags. Tags like [nervous], [sad], [angry],
# [excited] or [whispers] often make v3 go breathy, whisper, or change the
# voice's character, so they're never sent. Everything else is dropped and
# the line is read with normal delivery.
# ---------------------------------------------------------------------------
SUPPORTED_V3_TAGS = {
    "happy", "sad", "angry", "excited", "curious", "surprised", "scared",
    "whispers", "shouts", "sighs", "laughs", "crying", "sarcastic",
    "mischievously", "nervous", "confident", "tired", "disgusted",
}

# Only these ever reach the API.
SAFE_OUTPUT_TAGS = {"happy", "curious", "surprised", "confident"}

TAG_ALIAS_MAP = {
    "warm": None, "welcoming": "happy", "friendly": "happy",
    "helpful": None, "curious": "curious", "thoughtful": None,
    "encouraging": "happy", "pleased": "happy", "delighted": "happy",
    "confirming": None, "hopeful": None, "precise": None,
    "acknowledging": None, "informative": None, "descriptive": None,
    "reassuring": None, "surprised": "surprised", "accepting": None,
    "decisive": None, "satisfied": "happy", "brisk": None,
    "businesslike": None, "careful": None, "calculating": None,
    "relieved": "happy", "apologetic": None, "grateful": "happy",
    "closing": None, "concluding": None,
    "clear": None, "matter-of-fact": None, "steady": None, "guiding": None,
    "confident": "confident", "presenting": None, "proud": "confident",
    "reflective": None, "gentle": None, "cautionary": None,
    "transitional": None, "engaging": None, "contrasting": None,
    "explanatory": None, "measured": None, "emphatic": None,
    "impressed": "surprised", "balanced": None, "forward-looking": None,
    "illustrative": None, "rhetorical": None, "intrigued": "curious",
    "organizing": None, "probing": "curious",
    "recalling": None, "conceding": None, "explaining": None,
    "adjusting": None, "disagreeing": None, "firm": None,
    "gently teasing": None, "brief": None, "content": "happy",
    "calm": None, "final": None, "announcer": None, "quick": None,
    "considering": None, "agreeing": None, "hesitant": None,
    "tentative": None, "a little tentative": None, "soft": None,
    "practical": None, "excited": "happy",
}


def _map_one_tag(raw: str) -> str | None:
    key = raw.strip().lower()
    mapped = TAG_ALIAS_MAP.get(key, key if key in SUPPORTED_V3_TAGS else None)
    return mapped if mapped in SAFE_OUTPUT_TAGS else None

# ---------------------------------------------------------------------------
# Timing / grouping
# ---------------------------------------------------------------------------
GAP_BETWEEN_TURNS_MS = 450          # natural pause between speaker turns
GAP_AFTER_NARRATOR_MS = 700

# Consecutive lines by the same speaker are sent to ElevenLabs as ONE request
# (up to this many characters). Fewer, longer requests = the voice stays the
# same person instead of being re-interpreted on every short line.
MAX_CHARS_PER_REQUEST = 1500

OUTPUT_DIR = "output"
CACHE_DIR = "cache"